version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - sqlite-container
    environment:
      - NODE_ENV=$UI_NODE_ENV=$API_NODE_ENV
      - DB_CONNECTION_STRING=/data/db.sqlite 
      - PORT=$API_PORT
      - FRONT_END_URI=$REACT_APP_URI
    volumes:
      - ./sqlite/database:/data  

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - $UI_PORT:$UI_PORT
    environment:
      - NODE_ENV=$UI_NODE_ENV
      - PORT=$UI_PORT
      - REACT_APP_API_URL=$REACT_APP_API_HOST
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true

  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   restart: unless-stopped
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - backend
  #     - frontend

  sqlite-container:
    container_name: sqlite-container
    build: 
      context: ./sqlite
    image: sqlite_db
    

