version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - sqlite-container
    environment:
      - NODE_ENV=$UI_NODE_ENV=$API_NODE_ENV
      - DB_CONNECTION_STRING=/data/db.sqlite 
      - PORT=$API_PORT
      - FRONT_END_URI=$REACT_APP_URI
    volumes:
      - ./sqlite/database:/data  

  frontend_build:
    build:
      context: ./frontend
    environment:
      - NODE_ENV=$UI_NODE_ENV
      - REACT_APP_API_URL=$REACT_APP_API_HOST
    volumes:
      - ./frontend/build:/app/build
      - /app/node_modules
    
  frontend_server:
    image: nginx:alpine
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - 80:80

  sqlite-container:
    build: 
      context: ./sqlite
    image: sqlite_db
    container_name: sqlite-container

