version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - sqlite-container
    environment:
      - NODE_ENV=$UI_NODE_ENV=$API_NODE_ENV
      - DB_CONNECTION_STRING=/data/db.sqlite 
      - PORT=$API_PORT
      - FRONT_END_URI=$REACT_APP_URI
    volumes:
      - ./sqlite/database:/data  
    networks:
      - backend

  frontend:
    container_name: frontend
    hostname: frontend
    build:
      context: ./frontend
    environment:
      - NODE_ENV=$UI_NODE_ENV
      - PORT=$UI_PORT
      - REACT_APP_API_URL=$REACT_APP_API_HOST
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - backend

  sqlite-container:
    container_name: sqlite-container
    build: 
      context: ./sqlite
    image: sqlite_db
    networks:
      - backend

  nginx:
    image: nginx
    restart: unless-stopped
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
    networks:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email 2132258@champlaincollege.qc.ca -d myportfolio.business --agree-tos
    networks:
      - backend

networks:
  backend:
    driver: bridge
