version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - sqlite-container
    environment:
      - DB_CONNECTION_STRING=/data/initial-db.sqlite
      - PORT=$API_PORT
      - FRONT_END_URI= $REACT_APP_URI
    volumes:
      - sqlite_data:/data

  frontend:
    build:
      context: ./frontend
    ports:
      - $UI_PORT:$UI_PORT
    environment:
      - NODE_ENV=$UI_NODE_ENV
      - PORT=$UI_PORT
      - REACT_APP_API_URL= $REACT_APP_API_HOST
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true

  sqlite-container:
    image: alpine:latest
    volumes:
      - ./sqlite/database:/data
    command: sh -c "apk --no-cache add sqlite && cp /data/initial-db.sqlite /data/db.sqlite && sqlite3 /data/db.sqlite < /data/init.sql && echo 'Initialization completed successfully' && tail -f /dev/null"
    container_name: sqlite-container

  sqlitebrowser:
    image: linuxserver/sqlitebrowser
    ports:
      - "3000:3000"
    depends_on:
      - sqlite-container
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - ENABLE_UWSGI=true
    volumes:
      - sqlite_data:/data/db
    container_name: sqlitebrowser

volumes:
  sqlite_data:
    external: true
